name: 'CORRECT'
description: 'Execute function on a Globus Compute Endpoint.'
inputs:
  client_id:
    description: Globus Client ID to use
    required: true
  client_secret:
    description: Globus Client secret to use
    required: true
  endpoint_uuid:
    description: Globus Compute endpoint UUID to run tasks on
    required: true
  user_endpoint_config:
    description:
      Configuration values for endpoint that are described and allowed by
      endpoint administrators
    required: false
    default: '{}'
  clone_endpoint_config:
    description:
      Configuration values for endpoint that are described and allowed by
      endpoint administrators. This config is only used for the cloning of the
      repo. If no value is provided, it will default to using the
      user_endpoint_config
    required: false
    default: '{}'
  resource_specification:
    description: Resource requirements for individual task execution
    required: false
    default: '{}'
  function_uuid:
    description:
      Function UUID to run on endpoint. Is overidden if shell_cmd is provided.
    required: false
    default: ''
  shell_cmd:
    description:
      Shell command to execute using Globus Compute. Takes priority over
      function_uuid and ignores any specified args and kwargs.
    required: false
    default: ''
  args:
    description: Task input args specified as list of arguments
    default: '[]'
  kwargs:
    description: Task input kwargs specified as a dictionary of kwargs
    default: '{}'
outputs:
  response:
    description: Globus SDK HTTP response for task execution
  result:
    description:
      Task execution result. Is empty unless response status indicates task
      succeeded
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'check-circle'
  color: 'purple'
